# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - userManagement-ms

on:
  push:
    branches:
      - with_.env_files
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests
        working-directory: ./UserManagementComponent/userManagement-ms

      - name: List build output (debug)
        run: ls -R ./UserManagementComponent/userManagement-ms/target

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'userManagement-ms'
          slot-name: 'Production'
          package: './UserManagementComponent/userManagement-ms/target/userManagement-ms-0.0.1-SNAPSHOT.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A5266B39BE6647119A991F8FE47D430F }}
